eight_points_guzzle:
    logging: true

    clients:
        finance_consult:
            base_url: '%gonetto.fc-api-client.base_api_url%'
            options:
                headers:
                    Accept: "application/json"
