eight_points_guzzle:
    logging: true

    clients:
        api_finance_consult:
            base_url: '%finance_consult_base_api_url%'
            options:
                headers:
                    Accept: "application/json"
