services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Gonetto\FCApiClientBundle\Service\CustomerClient:
    class:      Gonetto\FCApiClientBundle\Service\CustomerClient
    arguments:
      - '%gonetto_fc_api_client.api_access_token%'
      - '%gonetto_fc_api_client.api_path%'
      - '@eight_points_guzzle.client.finance_consult'
      - '@gonetto_fc_api_client.service.json_schema_check'
      - '@gonetto_fc_api_client.service.response_mapper'
    public: true

  gonetto_fc_api_client.service.response_mapper:
    class:      Gonetto\FCApiClientBundle\Service\ResponseMapper
    arguments: ['@symfony.component.yaml', '@doctrine.orm.entity_manager']

  gonetto_fc_api_client.service.json_schema_check:
    class:      Gonetto\FCApiClientBundle\Service\JSONSchemaCheck
