services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Gonetto\FCApiClientBundle\Service\ApiClient:
        class:      Gonetto\FCApiClientBundle\Service\ApiClient
        arguments:
            - '%gonetto_fc_api_client.api_path%'
            - '@eight_points_guzzle.client.finance_consult'
        public: true

    Gonetto\FCApiClientBundle\Service\JSONSchemaCheck:
        class:      Gonetto\FCApiClientBundle\Service\JSONSchemaCheck

    Gonetto\FCApiClientBundle\Service\ResponseMapper:
        class:      Gonetto\FCApiClientBundle\Service\ResponseMapper

    Gonetto\FCApiClientBundle\Service\CustomerClient:
        class:      Gonetto\FCApiClientBundle\Service\CustomerClient
        arguments:
            - '%gonetto_fc_api_client.api_access_token%'
            - '@Gonetto\FCApiClientBundle\Service\ApiClient'
            - '@Gonetto\FCApiClientBundle\Service\JSONSchemaCheck'
            - '@Gonetto\FCApiClientBundle\Service\ResponseMapper'
        public: true
