services:
  Gonetto\FCApiClientBundle\Client\CustomerClient:
    class:      Gonetto\FCApiClientBundle\Client\CustomerClient
    arguments:
      - '%gonetto.fc-api-client.api_access_token%'
      - '%gonetto.fc-api-client.api_path%'
      - '@eight_points_guzzle.client.finance_consult'
      - '@gonetto.fc-api-client.service.json_schema_check'
      - '@gonetto.fc-api-client.service.response_mapper'

  test_alias.gonetto.fc-api-client.client.customer:
    alias: 'Gonetto\FCApiClientBundle\Client\CustomerClient'
    public: true

  gonetto.fc-api-client.service.response_mapper:
    class:      Gonetto\FCApiClientBundle\Service\ResponseMapper
    arguments: ['@symfony.component.yaml', '@doctrine.orm.entity_manager']

  test_alias.gonetto.fc-api-client.service.response_mapper:
    alias: 'gonetto.fc-api-client.service.response_mapper'
    public: true
