services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $token: '%gonetto_fc_api_client.api_access_token%'
      $financeConsultApiPath: '%gonetto_fc_api_client.api_path%'

  # Using alias to enable autowiring
  gonetto.fc_api_client.customer_update_request_factory:
    class: Gonetto\FCApiClientBundle\Service\CustomerUpdateRequestFactory

  Gonetto\FCApiClientBundle\Model\CustomerUpdateRequest:
    factory: ['@gonetto.fc_api_client.customer_update_request_factory', 'createRequest']
    class: Gonetto\FCApiClientBundle\Model\CustomerUpdateRequest
    shard: false

  # Using alias to enable autowiring
  gonetto.fc_api_client.data_request_factory:
    class: Gonetto\FCApiClientBundle\Service\DataRequestFactory

  Gonetto\FCApiClientBundle\Model\DataRequest:
    factory: ['@gonetto.fc_api_client.data_request_factory', 'createRequest']
    class: Gonetto\FCApiClientBundle\Model\DataRequest
    shard: false

  # Using alias to enable autowiring
  gonetto.fc_api_client.file_request_factory:
    class: Gonetto\FCApiClientBundle\Service\FileRequestFactory

  Gonetto\FCApiClientBundle\Model\FileRequest:
    factory: ['@gonetto.fc_api_client.file_request_factory', 'createRequest']
    class: Gonetto\FCApiClientBundle\Model\FileRequest
    shard: false

  Gonetto\FCApiClientBundle\Service\JmsSerializerFactory: ~

  JMS\Serializer\Serializer:
    factory: 'Gonetto\FCApiClientBundle\Service\JmsSerializerFactory:createSerializer'
    class: JMS\Serializer\Serializer

  GuzzleHttp\Client: '@eight_points_guzzle.client.finance_consult'

  Gonetto\FCApiClientBundle\Service\DataClient:
    public: true
