services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Gonetto\FCApiClientBundle\Model\DataRequest:
        class: Gonetto\FCApiClientBundle\Model\DataRequest
        factory: 'Gonetto\FCApiClientBundle\Service\DataRequestFactory:createRequest'
        shard: false
        arguments: ['%gonetto_fc_api_client.api_access_token%']

    Gonetto\FCApiClientBundle\Model\FileRequest:
        class: Gonetto\FCApiClientBundle\Model\FileRequest
        factory: 'Gonetto\FCApiClientBundle\Service\FileRequestFactory:createRequest'
        shard: false
        arguments: ['%gonetto_fc_api_client.api_access_token%']

    Gonetto\FCApiClientBundle\Model\CustomerUpdateRequest:
        class: Gonetto\FCApiClientBundle\Model\CustomerUpdateRequest
        factory: 'Gonetto\FCApiClientBundle\Service\CustomerUpdateRequestFactory:createRequest'
        shard: false
        arguments: ['%gonetto_fc_api_client.api_access_token%']

    JMS\Serializer\Serializer:
        class: JMS\Serializer\Serializer
        factory: 'Gonetto\FCApiClientBundle\Service\JmsSerializerFactory:createSerializer'

    Gonetto\FCApiClientBundle\Service\DataClient:
        class:      Gonetto\FCApiClientBundle\Service\DataClient
        arguments:
            - '%gonetto_fc_api_client.api_path%'
            - '@eight_points_guzzle.client.finance_consult'
            - '@Gonetto\FCApiClientBundle\Model\CustomerUpdateRequest'
            - '@Gonetto\FCApiClientBundle\Model\DataRequest'
            - '@Gonetto\FCApiClientBundle\Model\FileRequest'
            - '@JMS\Serializer\Serializer'
        public: true
v
